version: '3.4'

services:
  node1:
    image: asteroidbelt:dev
    container_name: AsteroidBelt.Web
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AsteroidBelt.Web"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_node1$
    volumes:
      - D:\dev\projects\akka-asteriod-belt\source\AsteroidBelt.Web:/app
      - D:\dev\projects\akka-asteriod-belt:/src
      - C:\Users\Etti\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_node1$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_node1$ \"/app/bin/Debug/net5.0/AsteroidBelt.Web.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  node2:
    image: asteroidbelt:dev
    container_name: AsteroidBelt.Web_1
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AsteroidBelt.Web"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_node2$
    volumes:
      - D:\dev\projects\akka-asteriod-belt\source\AsteroidBelt.Web:/app
      - D:\dev\projects\akka-asteriod-belt:/src
      - C:\Users\Etti\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_node2$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_node2$ \"/app/bin/Debug/net5.0/AsteroidBelt.Web.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  seed:
    image: asteroidbelt:dev
    container_name: AsteroidBelt.Web_2
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AsteroidBelt.Web"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_seed$
    volumes:
      - D:\dev\projects\akka-asteriod-belt\source\AsteroidBelt.Web:/app
      - D:\dev\projects\akka-asteriod-belt:/src
      - C:\Users\Etti\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_seed$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_seed$ \"/app/bin/Debug/net5.0/AsteroidBelt.Web.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
